### ISSUE TITLE
env contains HTTP_HTTP_X_MOBILE_TOKEN instead of HTTP_X_MOBILE_TOKEN

### ISSUE THREAD

**Issue by drnic** [mattetti/sinatra-web-api-example#3]
In the branch 'mobile' I've started a mobile-only API and some test cases.

Oddly, the env keys include `HTTP_HTTP_X_MOBILE_TOKEN` instead of just `HTTP_X_MOBILE_TOKEN`. Thoughts why?

**Comment by drnic** [comment]
See https://github.com/mattetti/sinatra-web-api-example/blob/mobile/lib/auth_helpers.rb#L22

**Comment by mattetti** [comment]
Yes, this is due to the way Rack handles X Headers :(
I should fix `TestApi` to remove the HTTP that gets added to the header. I'll do that right now, good catch.

**Comment by mattetti** [comment]
fixed on the main brach: commit: 61db8b6478
